[puppet]
# specify which puppet is using
puppet = "macPro"

  [puppet.macPro]
  # your wechaty-puppet-macPro token
  name = "macPuppet"
  token = "foo"

  [puppet.hostie]
  # your wechaty-puppet-hostie token
  name = "winPuppet"
  token = "foo"

  [puppet.padPlus]
  # your wechaty-puppet-padplus token
  name = "padPuppet"
  token = "foo"

[db]
# mongoDb params
name = "wechaty"
addr = "localhost"
port = 27017

[server]
# server address
addr = "127.0.0.1"
ssl = false

  [server.web]
  # for web api
  port = 4000

  [server.webSocket]
  # for webSocket
  port = 8080

[miniProgram]
# default account id (gh_xxx) for forwarding miniProgram
accId = "foo"
